---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: teamoon Community Support
    url: https://github.com/JuanVilla424/teamoon/discussions
    about: Please ask and answer questions here.
  - name: teamoon Security Reports
    url: https://juanvilla424.github.io/teamoon/SECURITY
    about: Please report security vulnerabilities here.
